# ==============================================================================
# Script Name: 5_tests/stress_render.R
# Purpose:     The thin, slow layer of phase 4. The function-level harness
#              (5_tests/stress_harness.R) exercises the chart logic; this script
#              actually KNITS each production template once, against its single
#              nastiest variant, to catch failures that only appear at the Rmd
#              layer — YAML param coercion, pandoc, the CSS-injection chunk — that
#              a direct viz_*() call would never touch.
#
# Reading it:  a "FAILED" render here is often the CORRECT outcome — e.g. the
#              choropleth SHOULD stop on unmatchable district names. The job is
#              to confirm every failure is a clean R stop surfaced through the
#              template (a clear message), NOT a pandoc/YAML explosion. Read each
#              reported message; cross-check against the harness's clean-error rows.
#
# SIDE EFFECT: templates hard-code fig.path to 4_output/figures, so this run
#              overwrites production figures there with throwaway stress figures.
#              That directory is gitignored and fully regenerated by the next
#              production knit (and cleared by 5_tests/snapshot.R), so it is
#              harmless — just re-run 2_R/2.2_master_knit.R afterwards if you want
#              a clean 4_output. HTML goes to 5_tests/stress_output/ (gitignored),
#              never overwriting the real reports.
#
# Run:         source(here::here("5_tests", "stress_data_generator.R"))  # first
#              source(here::here("5_tests", "stress_render.R"))
# renv owns packages — nothing is installed here.
# ==============================================================================

library(here)
source(here::here("2_R", "2.5_helpers.R"))   # cerp_render_one + house helpers
source(here::here("5_tests", "stress_spec.R"))
cerp_require("cli")

template_dir <- here::here("3_templates")
stress_dir   <- here::here("5_tests", "stress_data")
out_dir      <- here::here("5_tests", "stress_output")

if (!file.exists(file.path(stress_dir, "_manifest.csv"))) {
  stop("No stress variants found. Run 5_tests/stress_data_generator.R first.",
       call. = FALSE)
}
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

cli::cli_h1("Render-level stress pass — one nastiest variant per template")
cli::cli_alert_info(paste0(
  "A FAILED render can be the CORRECT loud stop; read the message to confirm ",
  "it is a clean template error, not an Rmd-layer (pandoc/YAML) break."))
cat("\n")

n_render <- 0L; n_fail <- 0L
for (id in names(stress_templates)) {
  entry <- stress_templates[[id]]
  stem  <- sub("\\.csv$", "", entry$data)
  variant_file <- file.path(stress_dir, paste0(stem, "__", entry$nastiest, ".csv"))

  if (!file.exists(variant_file)) {
    cli::cli_alert_warning("{id}: nastiest variant missing ({basename(variant_file)}) — skipped")
    next
  }

  out_file <- paste0(sub("\\.Rmd$", "", entry$template), "__", entry$nastiest, ".html")

  # Override ONLY data_path (as render_config.yml does); every other param keeps
  # its template default. cerp_render_one isolates the env and tryCatch-continues.
  ok <- cerp_render_one(
    input       = file.path(template_dir, entry$template),
    output_dir  = out_dir,
    output_file = out_file,
    params      = list(data_path = variant_file),
    label       = paste0(id, "  (", entry$nastiest, ")")
  )
  if (isTRUE(ok)) n_render <- n_render + 1L else n_fail <- n_fail + 1L
  cat("\n")
}

cli::cli_rule()
cli::cli_alert_success("Render-level pass complete: {n_render} knit, {n_fail} stopped.")
cli::cli_alert_info(paste0(
  "Stopped renders are expected where the nastiest input should be rejected. ",
  "HTML (for the ones that knit) is in 5_tests/stress_output/. Re-run ",
  "2_R/2.2_master_knit.R to restore a clean 4_output/figures."))
