---
title: "`r params$report_title`"
author: "`r params$report_author`"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    toc: false
    code_folding: hide
params:
  # Master Data Path
  data_path: !r here::here("1_data", "master_micro_survey.csv")

  # Variables
  category_var: "attrition_status"

  # Array Math
  scale_factor: 50   # 1 dot = X units. Adjust this so the total number of dots on screen is around 100.

  # Policy-Facing Labels
  unit_name: "Households"
  metric_name: "Survey Completion & Attrition"

  # --- Report Text (all editable; leave "" to use the smart default) ---
  report_title: "Sample Attrition: Icon Array"
  report_author: "Ibraheem Saqib Ellahi"
  chart_title: ""
  chart_subtitle: ""
  source_note: "Generated via CERP Analytics Template"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  dev.args = list(bg = "#FAF9F6"),
  fig.path = paste0(here::here("4_output", "figures"), "/"),
  fig.width = 8,
  fig.height = 6,
  fig.retina = 3
)
```

```{r cerp-style, echo=FALSE, results='asis'}
cat("<style>", readr::read_file(here::here("2_R", "cerp_style.css")), "</style>")
```

```{r load-and-prep}
library(tidyverse)

source(here::here("2_R", "2.5_helpers.R"), local = TRUE)

# Load data (headers/values whitespace-scrubbed) and validate YAML params.
# All data scrubbing + plotting now lives in viz_icon_array() (2_R/2.6_viz_functions.R).
raw_data <- cerp_load(params$data_path)
cerp_validate(raw_data, params[grepl("_var$", names(params))])
```


```{r plot-icon-array}
source(here::here("2_R", "2.0_setup_theme.R"), local = TRUE)
source(here::here("2_R", "2.6_viz_functions.R"), local = TRUE)

viz_icon_array(
  data           = raw_data,
  category_var   = params$category_var,
  scale_factor   = params$scale_factor,
  unit_name      = params$unit_name,
  metric_name    = params$metric_name,
  chart_title    = params$chart_title,
  chart_subtitle = params$chart_subtitle,
  source_note    = params$source_note
)
```
